import type { TechQuestion } from './bank.js';

// Platform knowledge: the web, security, testing and delivery questions that
// show up in almost every backend, full-stack and product-engineering screen,
// regardless of language.
//
// Authored against what current interview write-ups say is actually asked
// (HTTP semantics and status codes, idempotency framed through payment
// retries, auth token storage and XSS, parameterised queries, CORS, caching,
// pagination, rate limiting, test pyramid, CI and rollback). The bar
// throughout is application, not definitions: every follow-up pushes from
// "what is it" to "what breaks, and what would you do".

export const PLATFORM_BANK: TechQuestion[] = [
  // --- Web and HTTP ---------------------------------------------------------
  {
    id: 'web-status-codes',
    topic: 'web',
    question: "A client POSTs to your API and something goes wrong. Walk me through which status code you'd return, and why it matters.",
    followUps: [
      'When would you use 422 over 400?',
      'The client retries on 500. Should they retry on 400? Why not?',
      "Your service is fine but the database it depends on is down. What comes back, and what header goes with it?",
    ],
    answerKey: [
      '4xx means the caller must change something; 5xx means the server failed and the same request might succeed later.',
      '400 for a malformed request the parser rejected; 422 (or 400, consistently) for well-formed but semantically invalid input.',
      '401 means not authenticated, 403 means authenticated but not allowed; confusing them leaks information and breaks client retry logic.',
      '409 for a conflict with current state, 404 for a missing resource, 429 when rate limited.',
      'Status codes are a contract clients automate against: retry, alert and circuit-breaker behaviour keys off 4xx versus 5xx.',
      '503 with Retry-After for a dependency outage, so clients back off instead of hammering.',
    ],
    depth: 1,
    escalation: null,
  },
  {
    id: 'web-idempotency',
    topic: 'web',
    question: "A payment request times out and the client retries. How do you make sure the customer is only charged once?",
    followUps: [
      'Where does the idempotency key come from, and how long do you keep it?',
      'Two identical requests arrive at the same moment on different servers. What happens?',
      'What do you return for the second request: the original response, or a conflict?',
    ],
    answerKey: [
      'The client generates an idempotency key per logical operation and sends it on every retry of that operation.',
      'The server records the key with the result of the first completed request, inside the same transaction as the effect.',
      'Concurrent duplicates are handled by a unique constraint on the key, so the loser waits for or reads the winner\'s result.',
      'Return the original stored response so retries are invisible to the caller.',
      'GET, PUT and DELETE are idempotent by HTTP semantics; POST is not, which is exactly why it needs a key.',
      'Keys expire after a bounded window (hours to days) that comfortably exceeds client retry windows.',
    ],
    depth: 3,
    escalation: 'Sketch the table and the write path that guarantees exactly-once effect under concurrent retries.',
  },
  {
    id: 'web-cors',
    topic: 'web',
    question: "A front-end developer says your API is 'blocked by CORS'. What is actually happening?",
    followUps: [
      'What is the preflight request, and what triggers one?',
      "They ask you to just set Access-Control-Allow-Origin to *. When is that a bad idea?",
      'Does CORS protect your server?',
    ],
    answerKey: [
      'CORS is enforced by the browser, not the server: the request often reaches the server and the browser hides the response.',
      'A preflight OPTIONS request is sent for non-simple methods, custom headers or certain content types.',
      'The server answers with Allow-Origin, Allow-Methods, Allow-Headers and optionally Allow-Credentials.',
      'Wildcard origin cannot be combined with credentials, and it defeats the point when the API is authenticated by cookie.',
      'CORS protects users of other sites from your credentials being used cross-origin; it is not server-side authorisation.',
      'Non-browser clients (curl, mobile, server to server) ignore CORS entirely.',
    ],
    depth: 2,
    escalation: null,
  },
  {
    id: 'web-caching-headers',
    topic: 'web',
    question: 'How would you cache an API response that changes a few times a day?',
    followUps: [
      'Cache-Control max-age versus ETag: when do you reach for each?',
      'What does a conditional request look like end to end?',
      'You deploy a fix and everyone still sees the old data for an hour. What went wrong, and how do you avoid it next time?',
    ],
    answerKey: [
      'Cache-Control controls whether and how long a response may be reused; ETag or Last-Modified enable revalidation.',
      'A conditional GET sends If-None-Match with the ETag; the server answers 304 with no body when unchanged.',
      'public versus private matters when a shared cache or CDN sits in front of authenticated responses.',
      'stale-while-revalidate serves the cached copy while refreshing in the background.',
      'Long max-age with no invalidation path is the usual cause of stale data after a deploy; versioned URLs or short TTL plus ETag avoid it.',
      'no-store for anything sensitive; no-cache means revalidate, not "do not cache".',
    ],
    depth: 2,
    escalation: null,
  },
  {
    id: 'web-pagination',
    topic: 'web',
    question: 'Your list endpoint returns ten million rows. How do you paginate it?',
    followUps: [
      'What goes wrong with OFFSET on page 5000?',
      'A row is inserted while the user is on page 3. What do they see?',
      'How do you paginate a feed sorted by a non-unique column?',
    ],
    answerKey: [
      'Offset pagination makes the database scan and discard offset rows, so deep pages get linearly slower.',
      'Cursor or keyset pagination filters on the last seen sort key, which uses the index and stays constant time.',
      'Offset pagination can skip or duplicate rows when the underlying data changes between pages; cursors are stable.',
      'A non-unique sort column needs a tiebreaker (typically the primary key) so the cursor is deterministic.',
      'The cursor should be opaque and encode the sort position, not a raw offset.',
      'Always cap page size server-side rather than trusting the client.',
    ],
    depth: 2,
    escalation: 'Write the SQL for the keyset query, including the tiebreaker.',
  },
  {
    id: 'web-rate-limiting',
    topic: 'web',
    question: 'One customer is sending far more traffic than the rest and slowing everyone down. What do you do?',
    followUps: [
      'Token bucket, leaky bucket or fixed window: which, and why?',
      'What breaks about fixed windows at the boundary?',
      'Where do you keep the counters when you have twenty API servers?',
    ],
    answerKey: [
      'Rate limit per identity (API key, user, tenant), not just per IP, since NAT and proxies share addresses.',
      'Token bucket allows controlled bursts while capping the sustained rate, which matches real client behaviour.',
      'Fixed windows allow double the limit across a boundary; sliding windows or token buckets avoid that.',
      'Counters live in a shared store such as Redis, with atomic increments or a Lua script to avoid races.',
      'Answer 429 with Retry-After, and return limit and remaining headers so clients can self-regulate.',
      'Distinguish rejecting excess traffic from queueing it; queueing turns a rate problem into a latency problem.',
    ],
    depth: 3,
    escalation: null,
  },
  {
    id: 'web-rest-vs-rpc',
    topic: 'web',
    question: 'When would you build an internal service with gRPC instead of REST over JSON?',
    followUps: [
      'What do you lose by choosing gRPC?',
      'How do you evolve a schema without breaking existing callers?',
      'Would you expose it directly to a browser?',
    ],
    answerKey: [
      'gRPC gives a typed contract, code generation, binary framing and streaming over HTTP/2, which suits chatty internal service to service calls.',
      'REST over JSON is easier to debug, cache and consume from anything, including curl and browsers.',
      'Protobuf evolution rules: add fields with new numbers, never reuse or renumber, treat unknown fields as ignorable.',
      'Browsers cannot speak raw gRPC without a proxy such as gRPC-Web or a gateway.',
      'HTTP caching semantics largely do not apply to gRPC; you build your own.',
      'The decision is usually about who the consumer is, not about performance in the abstract.',
    ],
    depth: 3,
    escalation: null,
  },
  {
    id: 'web-browser-request',
    topic: 'web',
    question: 'A user says the page is slow. It takes four seconds before anything appears. How do you work out why?',
    followUps: [
      'Which of those seconds are network and which are rendering?',
      'What does a render-blocking resource do to first paint?',
      'The API call takes 200ms. Where did the rest of the time go?',
    ],
    answerKey: [
      'Split the time: DNS, TCP and TLS, time to first byte, then download, parse, render and hydrate.',
      'Time to first byte isolates server and network from front-end cost.',
      'Synchronous scripts and stylesheets in the head block parsing and first paint; defer, async or inlining critical CSS help.',
      'Waterfall charts expose serialised requests, where each depends on the previous one finishing.',
      'Compression, HTTP/2 multiplexing, CDN edge caching and connection reuse each address a different part of the waterfall.',
      'Measure before optimising: browser dev tools or real user monitoring, not guesses.',
    ],
    depth: 2,
    escalation: null,
  },

  // --- Security -------------------------------------------------------------
  {
    id: 'security-sql-injection',
    topic: 'security',
    question: "Someone builds a query by concatenating a search box's contents into a SQL string. What's the problem, and what's the fix?",
    followUps: [
      'Why is escaping the input yourself a worse answer than parameterising?',
      'You need the sort column to come from the user. Parameters cannot bind identifiers. Now what?',
      'What limits the damage if an injection does happen?',
    ],
    answerKey: [
      'Concatenation lets input change the parsed structure of the statement, not just its values.',
      'Parameterised queries or prepared statements send the query plan and the values separately, so values cannot become syntax.',
      'Hand-rolled escaping fails on encodings, edge cases and dialect differences; the database driver has already solved it.',
      'Identifiers cannot be parameterised, so validate them against an allowlist of known column names.',
      'Least privilege: the application database user should not own DDL or read tables it never touches.',
      'ORMs help only when you stay on the parameterised path; raw string fragments inside an ORM are just as exploitable.',
    ],
    depth: 1,
    escalation: 'Rewrite the vulnerable query safely, including the sort-column case.',
  },
  {
    id: 'security-xss',
    topic: 'security',
    question: "Explain XSS to me as if I'd never heard of it, then tell me how you'd prevent it in a codebase you own.",
    followUps: [
      'Stored versus reflected versus DOM-based: what actually differs?',
      'Where does Content Security Policy fit in?',
      'React escapes by default. Is a React app safe from XSS?',
    ],
    answerKey: [
      'XSS runs attacker-controlled script in another user\'s browser session, with that user\'s privileges.',
      'Stored XSS persists in your data; reflected comes back from the request; DOM-based never touches the server.',
      'Escape on output, per context: HTML body, attribute, URL and JavaScript contexts need different escaping.',
      'Content Security Policy is defence in depth: it limits what an injected script can do or load, it does not fix the injection.',
      'React escapes interpolated text, but dangerouslySetInnerHTML, injected URLs (javascript:) and third-party scripts reopen the hole.',
      'HttpOnly cookies keep session tokens out of reach of injected script; tokens in localStorage do not have that protection.',
    ],
    depth: 2,
    escalation: null,
  },
  {
    id: 'security-jwt-storage',
    topic: 'security',
    question: 'You are storing a JWT in the browser. Where do you put it, and what are you trading off?',
    followUps: [
      'What happens to that token if you have an XSS bug?',
      'How do you log someone out before the token expires?',
      'What is the refresh token for, and where does it live?',
    ],
    answerKey: [
      'localStorage is readable by any script on the page, so an XSS bug becomes account takeover.',
      'An HttpOnly, Secure, SameSite cookie is not script-readable, but reintroduces CSRF considerations.',
      'JWTs are self-validating, so revocation needs either short expiry plus refresh, or a server-side denylist.',
      'Short-lived access tokens with a longer-lived refresh token limit the damage window.',
      'Signature algorithm must be pinned server-side; accepting the token\'s own alg header (including "none") is a classic break.',
      'A JWT is signed, not encrypted: anything in the payload is readable by the holder.',
    ],
    depth: 3,
    escalation: null,
  },
  {
    id: 'security-password-storage',
    topic: 'security',
    question: 'How do you store user passwords?',
    followUps: [
      'Why not SHA-256?',
      'What is the salt for, and where do you keep it?',
      'Your database leaks tomorrow. What do you do?',
    ],
    answerKey: [
      'Use a purpose-built password hash: bcrypt, scrypt or Argon2, with a deliberately high work factor.',
      'General-purpose hashes such as SHA-256 are fast, which is exactly what an offline cracker wants.',
      'A per-user random salt, stored alongside the hash, defeats rainbow tables and makes identical passwords hash differently.',
      'A pepper is an application-side secret kept outside the database, adding protection if only the database leaks.',
      'Work factors need review over time as hardware improves; rehash on next successful login.',
      'On breach: force reset, invalidate sessions, notify, and check whether the leak included tokens or reset links as well.',
    ],
    depth: 1,
    escalation: null,
  },
  {
    id: 'security-authn-authz',
    topic: 'security',
    question: 'Walk me through the difference between authentication and authorisation, with an example of getting the second one wrong.',
    followUps: [
      'What is an insecure direct object reference?',
      'Where should the authorisation check live in a typical service?',
      'How do you test that a role cannot reach an endpoint it should not?',
    ],
    answerKey: [
      'Authentication proves who you are; authorisation decides what that identity may do.',
      'Broken object level authorisation, where changing an id in the URL returns someone else\'s record, is the most common API vulnerability in practice.',
      'The check belongs server-side on every request, close to the data access, not in the UI or a gateway alone.',
      'Deny by default: new endpoints should be unreachable until explicitly permitted.',
      'Ownership checks must be part of the query (where user_id = current user), not a separate lookup that can drift.',
      'Automated tests per role, including negative cases, are the only way this stays true after refactors.',
    ],
    depth: 2,
    escalation: null,
  },
  {
    id: 'security-tls',
    topic: 'security',
    question: 'What does HTTPS actually give you, and how does the browser know it can trust a server?',
    followUps: [
      'What is the certificate authority doing in that chain?',
      'What is the point of certificate expiry?',
      'Does TLS protect data at rest, or a compromised client?',
    ],
    answerKey: [
      'Confidentiality, integrity and server authentication for data in transit.',
      'The handshake authenticates the server with a certificate, then agrees symmetric session keys.',
      'Trust chains from the site certificate up through intermediates to a root the operating system or browser already trusts.',
      'Expiry limits the damage window of a compromised key and forces rotation.',
      'TLS terminates somewhere: past that point (load balancer, proxy) traffic may be plaintext unless re-encrypted.',
      'It does nothing for data at rest, a malicious client, or a compromised endpoint.',
    ],
    depth: 2,
    escalation: null,
  },
  {
    id: 'security-secrets',
    topic: 'security',
    question: 'Someone pushed an API key to the repository. What do you do, and how do you stop it happening again?',
    followUps: [
      'Is deleting the commit enough?',
      'Where should secrets live instead?',
      'How would you detect this automatically?',
    ],
    answerKey: [
      'Rotate the credential first: assume it is compromised the moment it is pushed, especially on a public repo.',
      'Rewriting history does not help if anyone cloned, forked or if a mirror or CI cached it.',
      'Secrets belong in a secret manager or environment configuration, injected at runtime, never in the image or repo.',
      'Pre-commit hooks and CI secret scanning catch most accidents before they land.',
      'Scope credentials narrowly and give them short lifetimes so rotation is routine rather than an incident.',
      'Audit what the key could reach, and check access logs for use during the exposure window.',
    ],
    depth: 1,
    escalation: null,
  },
  {
    id: 'security-csrf',
    topic: 'security',
    question: 'What is CSRF, and why does it stop being a concern for some APIs?',
    followUps: [
      'How does the SameSite cookie attribute change the picture?',
      'Why is a token in a header an effective defence?',
      'Does a bearer token in an Authorization header need CSRF protection?',
    ],
    answerKey: [
      'CSRF abuses the browser automatically attaching cookies to cross-site requests, so the victim\'s session performs an action they did not intend.',
      'It applies to cookie or other ambient credentials; it does not apply when the credential must be added by script.',
      'SameSite=Lax or Strict stops most cross-site sends, and Lax is the modern browser default.',
      'A synchroniser token or double-submit cookie works because an attacker cannot read the value cross-origin.',
      'A bearer token in an Authorization header is not sent automatically, so CSRF does not apply, but it is then script-readable.',
      'State-changing operations should never be reachable by GET.',
    ],
    depth: 3,
    escalation: null,
  },

  // --- Testing --------------------------------------------------------------
  {
    id: 'testing-pyramid',
    topic: 'testing',
    question: 'You join a service with no tests. What do you write first, and why?',
    followUps: [
      'What would make you write an integration test instead of a unit test?',
      'How do you decide what not to test?',
      'Is 100% coverage a goal?',
    ],
    answerKey: [
      'Start where the risk and the change rate are highest, usually the core domain logic and the paths that touch money or data integrity.',
      'Unit tests are fast and precise about where the break is; integration tests prove the wiring actually holds.',
      'A healthy suite has many fast tests and few slow end to end ones, because slow suites stop being run.',
      'Coverage is a smoke detector, not a goal: it measures executed lines, not asserted behaviour.',
      'Tests on stable, behaviour-defining interfaces survive refactors; tests on private internals resist them.',
      'The first test is also an argument for testability: seams, injected dependencies, no hidden global state.',
    ],
    depth: 1,
    escalation: null,
  },
  {
    id: 'testing-flaky',
    topic: 'testing',
    question: 'A test fails about one run in twenty. What do you do?',
    followUps: [
      'What are the usual causes?',
      'Would you retry it automatically in CI?',
      'How do you reproduce it locally?',
    ],
    answerKey: [
      'Treat flakiness as a real defect signal, not noise: it often reflects a genuine race in the code under test.',
      'Common causes: shared mutable state between tests, real time and sleeps, ordering dependence, network or clock reliance, unawaited async work.',
      'Blanket automatic retries hide the signal and let genuine races reach production.',
      'Quarantine loudly with a deadline rather than silently retrying, so it stays visible.',
      'Reproduce by running in a loop, randomising test order, and constraining concurrency to expose the race.',
      'Fix by controlling the non-determinism: injected clocks, deterministic seeds, explicit awaits, per-test isolation.',
    ],
    depth: 3,
    escalation: null,
  },
  {
    id: 'testing-mocks',
    topic: 'testing',
    question: 'When do you reach for a mock, and when is it the wrong tool?',
    followUps: [
      'What is the difference between a stub and a mock, practically speaking?',
      'What happens when the real dependency changes and your mock does not?',
      'How would you test code that calls a third-party HTTP API?',
    ],
    answerKey: [
      'Mock at the boundaries you do not own: network, clock, filesystem, payment provider.',
      'A stub returns canned data; a mock also asserts on the interaction, which couples the test to implementation details.',
      'Mocks drift from reality, which is what contract tests or a recorded fixture against the real API address.',
      'Over-mocking produces tests that pass while the system is broken, because nothing real is exercised.',
      'Prefer a fake (a working in-memory implementation) over a mock when the collaborator has real behaviour.',
      'For third-party HTTP: a local fake server or recorded responses, plus one real smoke test outside the fast suite.',
    ],
    depth: 2,
    escalation: null,
  },
  {
    id: 'testing-what-to-assert',
    topic: 'testing',
    question: 'How do you decide what a single test should assert?',
    followUps: [
      'What makes a test failure easy to diagnose?',
      'One assert per test: rule or superstition?',
      'How do you name tests?',
    ],
    answerKey: [
      'Assert the behaviour the caller depends on, not the shape of internal state.',
      'A good failure message names the behaviour, the input and the difference, so the cause is obvious without a debugger.',
      'One logical behaviour per test matters; mechanically one assert does not.',
      'Arrange, act, assert keeps a test readable by someone who did not write it.',
      'Names should read as a sentence about behaviour, so the report doubles as documentation.',
      'Test the edges that specifications gloss over: empty, one, duplicate, boundary and failure paths.',
    ],
    depth: 1,
    escalation: null,
  },
  {
    id: 'testing-property-based',
    topic: 'testing',
    question: 'Have you ever tested something where you could not enumerate the cases? How would you approach that?',
    followUps: [
      'What would be a good property for a sort function?',
      'How is that different from fuzzing?',
      'What do you do when a generated case fails?',
    ],
    answerKey: [
      'Property-based testing asserts invariants over generated inputs instead of fixed examples.',
      'Good properties: the output is sorted and is a permutation of the input; round trip encode then decode is identity; an operation is idempotent.',
      'Frameworks shrink a failing case to a minimal reproduction, which is most of the debugging value.',
      'Fuzzing targets crashes and undefined behaviour on adversarial input; property testing targets semantic invariants.',
      'A failing generated case should be pinned as a permanent regression test with its seed.',
      'It complements example tests rather than replacing them.',
    ],
    depth: 3,
    escalation: 'Name two properties you could assert about a cache implementation.',
  },
  {
    id: 'testing-legacy',
    topic: 'testing',
    question: 'You need to change a 500-line function with no tests. How do you start?',
    followUps: [
      'What is a characterisation test?',
      'How do you avoid changing behaviour while you refactor?',
      'What if the function reaches out to the network and the clock?',
    ],
    answerKey: [
      'Pin current behaviour first with characterisation tests, even where that behaviour looks wrong.',
      'Refactor in small, behaviour-preserving steps, running the pinned tests after each.',
      'Introduce seams by injecting the clock, the network client and other collaborators, so the function becomes testable without rewriting it.',
      'Separate the refactor commit from the behaviour-change commit so a bisect can tell them apart.',
      'Bugs found while pinning are recorded and fixed deliberately, not silently during the refactor.',
      'Coverage of the changed paths, not the whole file, is the practical bar.',
    ],
    depth: 2,
    escalation: null,
  },

  // --- Build, CI and deploys ------------------------------------------------
  {
    id: 'devops-deploy-strategy',
    topic: 'devops',
    question: 'How would you ship a risky change to a service that handles live traffic?',
    followUps: [
      'Blue-green or canary: what actually differs?',
      'What do you watch during the rollout, and what triggers a rollback?',
      'The change includes a database migration. Does that change your plan?',
    ],
    answerKey: [
      'Canary exposes a small share of traffic first and grows it while watching signals; blue-green switches wholesale between two environments.',
      'Decide rollback criteria before rolling out: error rate, latency percentiles, saturation, and a business metric.',
      'Feature flags separate deploying code from enabling behaviour, which makes the undo instant.',
      'Schema changes must be backwards compatible across the rollout: expand, migrate, contract, in separate deploys.',
      'A rollback is only real if it has been tested, including the data direction.',
      'Automate the rollback trigger where you can; humans are slow at 3am.',
    ],
    depth: 3,
    escalation: null,
  },
  {
    id: 'devops-ci-pipeline',
    topic: 'devops',
    question: 'What should happen automatically between someone opening a pull request and it reaching production?',
    followUps: [
      'Your pipeline takes 40 minutes. What do you do about it?',
      'What belongs in the pull request check versus the deploy pipeline?',
      'How do you keep the main branch always releasable?',
    ],
    answerKey: [
      'Build, fast tests, lint and type checks on every push; slower integration and end to end suites before release.',
      'Fast feedback matters more than completeness at the pull request stage; parallelise, cache dependencies and shard tests.',
      'Artifacts are built once and promoted through environments, not rebuilt per stage.',
      'Trunk-based development with small changes plus feature flags keeps main releasable.',
      'Pipelines should be reproducible: pinned versions, locked dependencies, no reliance on a developer machine.',
      'A red main branch is an emergency: revert first, investigate after.',
    ],
    depth: 2,
    escalation: null,
  },
  {
    id: 'devops-containers',
    topic: 'devops',
    question: 'What does a container actually give you that a virtual machine does not?',
    followUps: [
      'What is in an image, and why does layer order matter?',
      '"It works on my machine" still happens with containers. How?',
      'Why is running as root in a container discouraged?',
    ],
    answerKey: [
      'Containers share the host kernel and isolate with namespaces and cgroups; virtual machines virtualise hardware and run their own kernel.',
      'That makes containers lighter and faster to start, with weaker isolation boundaries than a hypervisor.',
      'An image is stacked read-only layers; ordering dictates cache reuse, so dependency installs go before source copies.',
      'Drift still comes from mounted config, environment variables, external services and unpinned base image tags.',
      'Root in a container is root on the host if isolation is escaped; run as an unprivileged user and drop capabilities.',
      'Images should be minimal: fewer packages means a smaller attack surface and faster pulls.',
    ],
    depth: 2,
    escalation: null,
  },
  {
    id: 'devops-observability',
    topic: 'devops',
    question: 'A user reports that something was slow twenty minutes ago. What do you need to have in place to answer them?',
    followUps: [
      'Logs, metrics and traces: what does each one answer that the others cannot?',
      'Why are averages a bad way to talk about latency?',
      'What would you alert on for a request-serving service?',
    ],
    answerKey: [
      'Metrics show trends and thresholds cheaply; logs carry per-event detail; traces show one request across services.',
      'Correlation ids or trace ids stitch the three together, and without them you are guessing.',
      'Averages hide the tail: p95 and p99 describe the experience users actually complain about.',
      'Alert on symptoms users feel (error rate, latency, saturation) rather than on every internal cause.',
      'Every alert should be actionable and have an owner; noisy alerts train people to ignore them.',
      'Cardinality discipline matters: per-user labels on metrics will take the metrics system down.',
    ],
    depth: 2,
    escalation: null,
  },
  {
    id: 'devops-git-workflow',
    topic: 'devops',
    question: 'Explain the difference between merge and rebase, and when you would use each.',
    followUps: [
      'When is rebasing actively dangerous?',
      'How do you undo a commit that is already on main and deployed?',
      'What makes a commit history useful six months later?',
    ],
    answerKey: [
      'Merge preserves the real branch topology; rebase replays commits onto a new base for a linear history.',
      'Rebasing rewrites commit identity, so never rebase a branch other people have based work on.',
      'To undo something already public, revert (a new commit) rather than reset and force-push.',
      'Small, coherent commits with messages explaining why beat large commits explaining what.',
      'Bisect is the payoff: a history of small, individually working commits finds a regression in log time.',
      'Conflicts during rebase are resolved per replayed commit, which is why long-lived branches hurt.',
    ],
    depth: 1,
    escalation: null,
  },
  {
    id: 'devops-incident',
    topic: 'devops',
    question: 'Production error rate jumps to 30% right after your deploy. Walk me through the next ten minutes.',
    followUps: [
      'When do you roll back versus push a fix forward?',
      'Who do you tell, and what do you tell them?',
      'What happens after it is over?',
    ],
    answerKey: [
      'Stop the bleeding first: roll back or disable the flag, then investigate with traffic restored.',
      'Diagnosing while users are down is the classic mistake; the artifact is still there to debug afterwards.',
      'Fix forward only when rollback is impossible (an irreversible migration) or demonstrably slower.',
      'Communicate early with impact, scope and next update time, rather than waiting for a root cause.',
      'One person coordinates, others investigate; unowned incidents duplicate work.',
      'Blameless postmortem afterwards, with action items that change the system, not reminders to be careful.',
    ],
    depth: 2,
    escalation: null,
  },
];
