import type { TechQuestion } from './bank.js';

// Language internals: the questions an interviewer asks once they know which
// language you claim. Each carries the language it belongs to, and the round
// samples only the ones matching the session language, so a Python session is
// never asked about the prototype chain.
//
// C++ has its own topic and bank; these cover the rest.

export const LANGUAGE_BANK: TechQuestion[] = [
  // --- Python ---------------------------------------------------------------
  {
    id: 'lang-py-gil',
    topic: 'langint',
    language: 'python',
    question: 'Python has a global interpreter lock. Given that, how would you make a slow program faster?',
    followUps: [
      'Your program spends its time waiting on HTTP calls. Threads or asyncio, and why?',
      'Now it is doing numeric work in a loop instead. What changes?',
      'What does the GIL actually protect?',
    ],
    answerKey: [
      'The GIL means one thread executes Python bytecode at a time, so threads do not give parallel CPU work.',
      'I/O-bound work still benefits from threads or asyncio, because the lock is released while waiting on I/O.',
      'CPU-bound work needs multiprocessing, a native extension that releases the GIL, or moving the hot loop into NumPy or C.',
      'asyncio is cooperative on one thread: concurrency without threads, and one blocking call stalls the whole loop.',
      'The GIL protects interpreter internals, notably reference counts, which is why removing it is hard.',
      'Free-threaded builds exist in recent versions, but assume the GIL unless the deployment says otherwise.',
    ],
    depth: 2,
    escalation: null,
  },
  {
    id: 'lang-py-generators',
    topic: 'langint',
    language: 'python',
    question: 'When would you write a generator instead of returning a list?',
    followUps: [
      'What does yield actually do to the function?',
      'What happens if you iterate the same generator twice?',
      'How would you process a 50GB file with this?',
    ],
    answerKey: [
      'A generator produces values lazily and holds one item at a time, so memory is constant rather than proportional to the data.',
      'yield turns the function into a state machine: calling it returns a generator, and execution resumes at the yield on each next().',
      'Generators are single-pass iterators: once exhausted they are done, unlike a list you can re-read.',
      'All generators are iterators; not all iterators are generators.',
      'Streaming a huge file means iterating lines or chunks and composing generators into a pipeline.',
      'The trade-off is no len(), no indexing, and harder debugging in exchange for memory and time to first result.',
    ],
    depth: 1,
    escalation: 'Write a generator pipeline that reads lines, parses them and yields only the matching records.',
  },
  {
    id: 'lang-py-mutability',
    topic: 'langint',
    language: 'python',
    question: 'A colleague writes def add_item(item, bucket=[]). What happens, and why?',
    followUps: [
      'When exactly is that default evaluated?',
      'What is the correct pattern?',
      'How does this relate to passing a list into a function and modifying it?',
    ],
    answerKey: [
      'The default is evaluated once at function definition, so every call without an argument shares the same list.',
      'The fix is a sentinel default of None and creating the list inside the function.',
      'Python passes object references by value: rebinding a parameter is local, mutating the object is visible to the caller.',
      'The same trap appears with dicts, sets and any mutable default, including class attributes shared across instances.',
      'Copy explicitly (list(x), copy.deepcopy) when the caller must not see mutations.',
      'Immutability (tuples, frozen dataclasses) removes the class of bug entirely.',
    ],
    depth: 1,
    escalation: null,
  },
  {
    id: 'lang-py-dict-internals',
    topic: 'langint',
    language: 'python',
    question: 'What has to be true about an object for it to work as a dictionary key?',
    followUps: [
      'What breaks if you mutate a key after inserting it?',
      'What is the contract between __eq__ and __hash__?',
      'Why do dicts keep insertion order now?',
    ],
    answerKey: [
      'Keys must be hashable: a stable __hash__ and a consistent __eq__.',
      'Objects that compare equal must hash equal, or lookups miss; the reverse is not required.',
      'Defining __eq__ without __hash__ makes a class unhashable by default, which is deliberate.',
      'Mutating a key after insertion changes its hash bucket expectation, so the entry becomes unreachable.',
      'Lists and dicts are unhashable for exactly that reason; tuples of immutables are fine.',
      'Modern CPython dicts store entries in a compact insertion-ordered array with a separate index table, which is why order is preserved and memory dropped.',
    ],
    depth: 3,
    escalation: null,
  },

  // --- JavaScript and TypeScript -------------------------------------------
  {
    id: 'lang-js-event-loop',
    topic: 'langint',
    language: 'javascript',
    question: 'Walk me through what the event loop does with a setTimeout of zero and a resolved promise in the same function.',
    followUps: [
      'Which runs first, and why?',
      'What happens to the UI if a promise callback runs a two-second loop?',
      'How would you break up work that must not block the page?',
    ],
    answerKey: [
      'Synchronous code runs to completion first; the call stack must empty before anything queued runs.',
      'Microtasks (promise callbacks, queueMicrotask) drain completely before the next macrotask (timers, I/O callbacks).',
      'So a resolved promise callback runs before a setTimeout(fn, 0) queued earlier.',
      'setTimeout zero is a minimum delay, not a guarantee; timers are clamped and queued.',
      'JavaScript is single-threaded per realm: a long synchronous callback blocks rendering and input regardless of where it was queued.',
      'Long work belongs in chunks yielded back to the loop, or in a Web Worker off the main thread.',
    ],
    depth: 2,
    escalation: null,
  },
  {
    id: 'lang-js-closures',
    topic: 'langint',
    language: 'javascript',
    question: 'Explain closures to me, and then tell me somewhere you have actually used one on purpose.',
    followUps: [
      'What does a closure capture: the value or the variable?',
      'The classic loop with var printing the same number: what is happening?',
      'Can a closure cause a memory leak?',
    ],
    answerKey: [
      'A closure is a function plus the scope it was defined in, kept alive after that scope returns.',
      'It captures the binding, not a snapshot of the value, which is what the var loop demonstrates.',
      'var is function-scoped so every iteration shares one binding; let creates a fresh binding per iteration.',
      'Practical uses: private state, memoisation, debounce and throttle, partial application, module pattern.',
      'A closure holding a large object (or a DOM node) keeps it reachable, so long-lived handlers can leak.',
      'Removing the listener or nulling the reference is what releases it.',
    ],
    depth: 1,
    escalation: 'Implement debounce, and say what the closure is holding.',
  },
  {
    id: 'lang-js-this',
    topic: 'langint',
    language: 'javascript',
    question: 'A method passed as a callback suddenly has the wrong this. What is going on?',
    followUps: [
      'What decides this at call time?',
      'How is an arrow function different?',
      'What do bind, call and apply do differently?',
    ],
    answerKey: [
      'In normal functions this is set by the call site: method call, plain call, new, or explicit binding.',
      'Extracting a method loses the receiver, so this becomes undefined in strict mode or the global object otherwise.',
      'Arrow functions have no own this; they close over the enclosing lexical this, which is why they work as callbacks.',
      'bind returns a new permanently bound function; call and apply invoke immediately, differing only in argument form.',
      'Class fields defined as arrow functions bind per instance, at the cost of one function per instance.',
      'new sets this to the freshly created object.',
    ],
    depth: 2,
    escalation: null,
  },
  {
    id: 'lang-js-promise-pitfalls',
    topic: 'langint',
    language: 'javascript',
    question: 'You need to call an API for each of 500 ids. How do you write it?',
    followUps: [
      'Why is awaiting inside a for loop often the wrong shape here?',
      'What is the difference between Promise.all and Promise.allSettled?',
      'How do you avoid firing all 500 at once?',
    ],
    answerKey: [
      'Sequential await serialises independent I/O, turning 500 parallel waits into 500 round trips end to end.',
      'Promise.all runs them concurrently but rejects as soon as one rejects, abandoning the results of the rest.',
      'allSettled returns every outcome, which is what you want when partial success is acceptable.',
      'Unbounded concurrency will exhaust sockets or trip the API rate limit, so bound it with a pool or chunking.',
      'An unhandled rejection in a fire-and-forget promise is a silent failure; every promise needs an owner.',
      'Sequential is correct when calls depend on each other or the API demands ordering.',
    ],
    depth: 2,
    escalation: 'Write a helper that runs an array of tasks with at most N in flight.',
  },
  {
    id: 'lang-ts-types',
    topic: 'langint',
    language: 'typescript',
    question: 'What does TypeScript actually give you at run time?',
    followUps: [
      'So how do you validate data coming from an API?',
      'any versus unknown: when does the difference matter?',
      'What is structural typing, and where does it surprise people?',
    ],
    answerKey: [
      'Nothing: types are erased at compile time, so they cannot validate untrusted input.',
      'External data needs a run-time schema check (a validator or hand-written type guard) that narrows to the declared type.',
      'any disables checking and spreads silently; unknown forces a narrowing check before use.',
      'TypeScript is structural: compatibility is by shape, not by declared name, so unrelated types can be assignable.',
      'That surprises people with excess property checks on literals, and with types that "fit" by accident.',
      'Generics plus narrowing keep type information flowing instead of casting it away.',
    ],
    depth: 2,
    escalation: null,
  },

  // --- Java -----------------------------------------------------------------
  {
    id: 'lang-java-equals-hashcode',
    topic: 'langint',
    language: 'java',
    question: 'You override equals but not hashCode. What breaks?',
    followUps: [
      'What is the actual contract between the two?',
      'Where does it show up at run time?',
      'How does a record change this?',
    ],
    answerKey: [
      'Objects that are equal must have equal hash codes; otherwise hash-based collections misbehave.',
      'HashMap and HashSet will fail to find an equal object because it lands in a different bucket.',
      'equals must be reflexive, symmetric, transitive, consistent, and false for null.',
      'Mutating a field used in hashCode after insertion makes the entry unreachable.',
      'Records generate both from the components, which removes the whole class of mistake.',
      'Objects.hash and Objects.equals cover the common implementations without hand-written null checks.',
    ],
    depth: 1,
    escalation: null,
  },
  {
    id: 'lang-java-collections-concurrency',
    topic: 'langint',
    language: 'java',
    question: 'Two threads write to the same HashMap. What happens, and what would you use instead?',
    followUps: [
      'Why is Collections.synchronizedMap often not the answer?',
      'What does ConcurrentHashMap do differently?',
      'What is the difference between a volatile field and an atomic one?',
    ],
    answerKey: [
      'An unsynchronised HashMap under concurrent writes can lose updates or corrupt internal structure.',
      'synchronizedMap serialises every operation on one lock, and compound actions (check then put) are still racy.',
      'ConcurrentHashMap locks per bin and provides atomic compound operations such as computeIfAbsent and putIfAbsent.',
      'volatile gives visibility and ordering for a single variable, not atomicity of read-modify-write.',
      'Atomic classes provide compare-and-set loops for lock-free updates of one value.',
      'Immutability, or confining state to one thread, avoids the question entirely.',
    ],
    depth: 2,
    escalation: null,
  },
  {
    id: 'lang-java-gc',
    topic: 'langint',
    language: 'java',
    question: 'Your service pauses for 400ms every few minutes. How do you find out whether it is garbage collection?',
    followUps: [
      'What is the difference between a young and a full collection?',
      'What would cause the old generation to keep growing?',
      'Does setting a bigger heap always help?',
    ],
    answerKey: [
      'GC logs and JVM metrics show pause duration, frequency and which collection ran.',
      'Generational collectors assume most objects die young; minor collections are cheap, full collections touch the old generation.',
      'Objects surviving repeated collections get promoted; a growing old generation suggests retention, caching or a leak.',
      'A bigger heap means fewer but longer pauses unless the collector is designed for it.',
      'Low-pause collectors trade throughput for shorter pauses; the right choice depends on the service.',
      'Allocation rate is often the real lever: allocating less beats tuning the collector.',
    ],
    depth: 3,
    escalation: null,
  },

  // --- Go -------------------------------------------------------------------
  {
    id: 'lang-go-goroutines',
    topic: 'langint',
    language: 'go',
    question: 'How do goroutines differ from threads, and how do you stop one?',
    followUps: [
      'What does an unbuffered channel send actually do?',
      'How do you cancel work that might block forever?',
      'What is a goroutine leak, and how would you notice one?',
    ],
    answerKey: [
      'Goroutines are user-space, multiplexed onto OS threads by the runtime scheduler, and start with a small growable stack.',
      'An unbuffered send blocks until a receiver is ready, which makes the channel a synchronisation point, not just a queue.',
      'Cancellation is by context: propagate ctx and select on ctx.Done() alongside the work.',
      'A goroutine blocked forever on a channel nobody reads never exits, and its memory is never reclaimed.',
      'Leaks show up as a rising goroutine count; pprof gives the stacks.',
      'The owner of a channel closes it, and closing signals completion rather than deleting the channel.',
    ],
    depth: 2,
    escalation: null,
  },
  {
    id: 'lang-go-slices',
    topic: 'langint',
    language: 'go',
    question: 'You pass a slice to a function, it appends to it, and the caller does not see the change. Explain.',
    followUps: [
      'What are the three parts of a slice header?',
      'When does append allocate a new array?',
      'What is the aliasing trap with subslices?',
    ],
    answerKey: [
      'A slice is a header of pointer, length and capacity, passed by value.',
      'append writes in place when capacity allows, and otherwise allocates a new array, leaving the caller pointing at the old one.',
      'So the callee\'s length change is invisible unless the slice is returned or a pointer is passed.',
      'Subslices share the same backing array, so writing through one can be seen through another.',
      'Growth amortises by roughly doubling, so repeated append is amortised constant time.',
      'copy, or a three-index slice expression limiting capacity, breaks the aliasing deliberately.',
    ],
    depth: 3,
    escalation: null,
  },

  // --- Rust -----------------------------------------------------------------
  {
    id: 'lang-rust-ownership',
    topic: 'langint',
    language: 'rust',
    question: 'Explain ownership and borrowing as if to someone coming from a garbage-collected language.',
    followUps: [
      'Why can you have many shared references but only one mutable one?',
      'What does a lifetime annotation actually tell the compiler?',
      'When would you reach for Rc or RefCell, and what do you give up?',
    ],
    answerKey: [
      'Every value has one owner; when the owner goes out of scope the value is dropped, so there is no collector and no manual free.',
      'Moves transfer ownership; borrows give temporary access without it.',
      'The aliasing rule (many readers or one writer) is what statically rules out data races and iterator invalidation.',
      'Lifetimes do not change how long data lives; they let the compiler check a reference never outlives its referent.',
      'Rc gives shared ownership with reference counting, RefCell moves the borrow check to run time and can panic.',
      'Rc plus RefCell is single-threaded; Arc plus Mutex is the multithreaded pairing, and Rc cycles still leak.',
    ],
    depth: 2,
    escalation: null,
  },
  {
    id: 'lang-rust-errors',
    topic: 'langint',
    language: 'rust',
    question: 'How do you handle errors in Rust, and when is unwrap acceptable?',
    followUps: [
      'What does the question-mark operator do?',
      'Option versus Result: what is each one saying?',
      'When would you actually want to panic?',
    ],
    answerKey: [
      'Errors are values: Result<T, E> makes failure part of the type, so it cannot be ignored silently.',
      'The question-mark operator propagates the error to the caller, converting it via From.',
      'Option models absence; Result models an operation that can fail with a reason.',
      'unwrap and expect panic on the failure case; acceptable in tests, prototypes, or where the invariant is genuinely guaranteed, with expect explaining why.',
      'Panic is for unrecoverable programmer error; a library should return errors rather than panic in the caller\'s process.',
      'Enum error types (or a wrapper crate) let callers match on cases instead of parsing strings.',
    ],
    depth: 3,
    escalation: null,
  },
];
